services:
  nginx:
    image: nginx:alpine
    container_name: nginx-si
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-si
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - database
  database:
    container_name: mysql-si
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./:/var/mysql
    ports:
      - "3306:3306"